### ISSUE TITLE
ASP MVC 5

### ISSUE THREAD

**Issue by weedkiller** [dncuug/scaffolder#15]
Hi can you support ASP MVC 5

**Comment by ernado-x** [comment]
Scaffolder implementing REST API, so you can use UI  based on any platform:  ASP.NET MVC, Angular, React, etc.

**Comment by weedkiller** [comment]
Thanks for reply, I am talking about ASP MVC with razor views.

**Comment by ernado-x** [comment]
This is not in project roadmap, but you free to implement it in your fork!

**Comment by weedkiller** [comment]
on the main page...

> _"Scaffolding - this is a way to automatically generate Web pages for each table in the database."_
